[package]
name = "dinf"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dinf"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
anyhow = "1.0.89"
thiserror = "1.0.63"
walkdir = "2.5.0"
glob = "0.3.1"
dirs = "4.0"
